# Generated by Django 3.1.3 on 2020-11-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_producttoorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttoorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_order', to='onlinestore.order'),
        ),
    ]
