# Generated by Django 3.1.3 on 2020-11-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0006_auto_20201124_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttoorder',
            name='products',
        ),
        migrations.AddField(
            model_name='producttoorder',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinestore.product'),
        ),
    ]
